version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: jacob-backend
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}

  frontend:
    image: jacob-frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - app-network
    environment:
      BACKEND_URL: ${BACKEND_URL}

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
