# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: gitlab-registry-credentials
      containers:
      - name: frontend
        image: "{{ CI_REGISTRY_IMAGE }}/frontend:latest"
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: {{ BACKEND_URL }}
        - name: BACKEND_PORT
          value: "8000"

        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
