apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # External port for HTTP traffic
      targetPort: 8501 # Forward traffic to container port 8501